spring:
  application:
    name: my-gateway-predicates-method-8085
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.75:8848
        username: nacos
        password: nacos
        ip: 192.168.0.75
    gateway:
      routes:
        - id: go_baidu
          uri: http://www.baidu.com/
          predicates:
            - Path=/**
            - Method=get

server:
  port: 8085
