spring:
  application:
    name: my-sentinel-begin-provider-8085
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.78:8848
        username: nacos
        password: nacos
        ip: 192.168.0.78
    sentinel:
      transport:
        # 使用8721端口和8888端口进行运行状态数据的传输
        port: 8721
        dashboard: 192.168.0.78:8888
      eager: true

server:
  port: 8085
