spring:
  application:
    name: my-nacos-provider-standalone-cluster-8080
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.72:8848
        username: nacos
        password: nacos
        ip: 192.168.0.72

server:
  port: 8080