spring:
  application:
    name: my-nacos-namespace-consumer-8091
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.72:8848
        username: nacos
        password: nacos
        #写命名空间ID，而不是命名空间名称
        namespace: ProjectA_Namespace_Id
        group: my-groupA

server:
  port: 8091
