spring:
  application:
    name: my-gateway-gatewayfilter-addrequestheader-8088
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.75:8848
        username: nacos
        password: nacos
        ip: 192.168.0.75
    gateway:
      routes:
        - id: go_baidu
          uri: http://192.168.0.75:8085/
          predicates:
            - Path=/**
          filters:
            - AddRequestHeader=xxxx,yyyy

server:
  port: 8088

logging:
  level:
    org.springframework.cloud.gateway.filter: trace
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.loadbalancer: trace
    org.springframework.web.reactive: trace
