spring:
  application:
    name: my-gateway-gatewayfilter-customfilter-8085
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.75:8848
        username: nacos
        password: nacos
        ip: 192.168.0.75
    gateway:
      routes:
        - id: go_baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/**
          filters:
            - MyRunTime=anyKey,anyValue

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway.filter: trace
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.loadbalancer: trace
    org.springframework.web.reactive: trace
